### ISSUE TITLE
ValueError: Unknown mat file type, version 105, 116

### ISSUE THREAD

**Issue by Scienceseb** [MehmetAygun/fusenet-pytorch#12]
Loading mat file ...
Traceback (most recent call last):
  File "/media/seb/SSD2/fusenet-pytorch/datasets/create_training_set.py", line 74, in <module>
    main()
  File "/media/seb/SSD2/fusenet-pytorch/datasets/create_training_set.py", line 71, in main
    create_dataset("nyu2")
  File "/media/seb/SSD2/fusenet-pytorch/datasets/create_training_set.py", line 66, in create_dataset
    create_nyu2()
  File "/media/seb/SSD2/fusenet-pytorch/datasets/create_training_set.py", line 16, in create_nyu2
    mapping =  sio.loadmat("nyuv2/nyuv2_40class_mapping.mat")["mapping"][0]
  File "/home/seb/anaconda3/envs/radar/lib/python3.6/site-packages/scipy/io/matlab/mio.py", line 207, in loadmat
    MR, file_opened = mat_reader_factory(file_name, appendmat, **kwargs)
  File "/home/seb/anaconda3/envs/radar/lib/python3.6/site-packages/scipy/io/matlab/mio.py", line 63, in mat_reader_factory
    mjv, mnv = get_matfile_version(byte_stream)
  File "/home/seb/anaconda3/envs/radar/lib/python3.6/site-packages/scipy/io/matlab/miobase.py", line 241, in get_matfile_version
    raise ValueError('Unknown mat file type, version %s, %s' % ret)
ValueError: Unknown mat file type, version 105, 116

Please resolve that error. Im using Python 3.7

**Comment by Scienceseb** [comment]
Downloading from web browser fix that

**Comment by hanyaoao** [comment]
Hi, I have also encountered this problem, could you please explain to me how to solve it

**Comment by aldiak** [comment]
Hi, I actually had to download the dataset again and it worked.

**Comment by N4SIRODDIN3** [comment]
This is probably a network issue. Try to redownload the data.

**Comment by N4SIRODDIN3** [comment]
This is probably an network issue. Try to redownload the data.
